pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "#approved-reviews-by>=1"
      - label!="WIP PR"
      - -title~=\[WIP\]
    actions:
      merge:
        method: merge
