name: NSFS Build

# Run Nightly and check if NS FS code was merged
on: 
  schedule:
    - cron: "0 0 * * *"

jobs:
  build-nsfs:
    runs-on: "ubuntu-latest"
    steps:
      - name: Get Current Date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d')"

      - name: Deploy gh CLI
        run: |
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
          sudo apt-add-repository https://cli.github.com/packages
          sudo apt update
          sudo apt install gh

      - name: Check NSFS Content
        id: check_nsfs_content
        run: |
          NEW_CONTENT_EXISTS=gh pr list -s merged -l "ns fs" --json mergedAt | grep $(date +'%Y-%m-%d') | wc -l
          echo ::set-output name=shouldbuild::${NEW_CONTENT_EXISTS}

      - name: Invoke Build on Operator Repo
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Manual Build Dispatch
          if: ${{ steps.check_nsfs_content.outputs.shouldbuild }} != 0
          repo: noobaa/noobaa-core
          token: ${{ secrets.GHACCESSTOKEN }}
          inputs: '{ "branch": "master", "tag": "nsfs" }' 
